#!/usr/bin/env sh

#🔋: discharging           -battery symbol
#🛑: not charging
#♻: stagnant charge
#🔌: charging              -plug symbol
#⚡: charged               -electricity symbol
#❗: battery very low!     -exclamation mark

capacity=$(acpi | sed "s/Battery 0: //g;s/remaining//g" | awk '{ print $2 }' | sed "s/%//g; s/,//g")
status=$(acpi | sed "s/Battery 0: //g;s/remaining//g" | awk '{ print $1 }' | sed "s/,//g")
remaining=$(acpi | sed "s/Battery 0: //g;s/remaining//g" | awk '{ print $3 }' | sed "s/,//g;s/%//g")
full=$(acpi | sed "s/Battery 0: //g;s/remaining//g" | awk '{ print $2 }' | sed "s/%//g")

	if [ $status == 'Full' ]; then
		icon='⚡'
	elif [ $status == 'Charging' ]; then
		icon='🔌'
	elif [ $capacity -le 15 ]; then
		icon='❗'
	elif [ "$capacity" -ge 85 ]; then
		icon='⚡'
	elif [ $status == 'Discharging' ]; then
		icon='🔋'
	fi


	if [ $status == 'Charging' ]; then
		echo $icon $capacity'%'
	elif [ $status == 'Full' ]; then
		echo $icon $full'%'
	elif [ $capacity -le 25 ]; then
		echo $icon $capacity'%' $remaining
	else
		echo $icon $capacity'%'
	fi

